// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace aspMvcDatabaseFirst1.Models
{
    public partial class Osoba
    {
        [Key]
        public int OsobaId { get; set; }

        [Required(ErrorMessage = "Unesite ime")]
        [StringLength(50, ErrorMessage = "Najvise 50 kaaktera", MinimumLength = 3)]
        public string Ime { get; set; }

        [Required(ErrorMessage ="Unesite prezime")]
        [StringLength(30,ErrorMessage = "Najvise 30 kaaktera",MinimumLength =3)]
        public string Prezime { get; set; }

        [Required(ErrorMessage = "Unesite adresu")]
        [StringLength(30, ErrorMessage = "Najvise 30 kaaktera", MinimumLength = 3)]
        public string Adresa { get; set; }

        [Required(ErrorMessage = "Unesite datum rodjenja")]
        [Display(Name = "Datum rodjenja")]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DatumRodjenja { get; set; }

       
 
        [Required(ErrorMessage = "Morate unijeti telefon")]
        [RegularExpression(@"\d{3}-\d{3}-\d{4}", ErrorMessage = "Telefon unesite u formatu 000-000-0000")]
        public string Telefon { get; set; }
    }
}