// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace aspMvcDatabaseFirst1.Models
{
    public partial class Osobadb2109Context : DbContext
    {
        public Osobadb2109Context()
        {
        }

        public Osobadb2109Context(DbContextOptions<Osobadb2109Context> opcije)
            : base(opcije)
        {
        }

        public virtual DbSet<Osoba> Osoba { get; set; }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Osoba>(entity =>
            {
                entity.Property(e => e.Telefon).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}